packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
  "@biomejs/biome": true
  "@tailwindcss/oxide": true
  "@sentry/cli": true
  core-js: false
  workerd: set this to true or false
  '@vscode/vsce-sign': set this to true or false
